/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.ryanchapin.hadoop.mapreduce.mrunit.avro;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum EventType { 
  GET, POST, PUT, LOGIN, LOGOUT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EventType\",\"namespace\":\"com.ryanchapin.hadoop.mapreduce.mrunit.avro\",\"symbols\":[\"GET\",\"POST\",\"PUT\",\"LOGIN\",\"LOGOUT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
